### ISSUE TITLE
TEST ISSUE Updating and finetuning the templates for issues and scrums

### ISSUE THREAD

**Issue by Bobmarinus** [FabianDumitrascu/Cooperative-Drone-Delivery-Cables#13]
### 1. Title:
Updating and finetuning the templates for issues and scrums

### 2. Description:
A detailed account of the issue including:

- **Background**: For the future, it is helpful if everything in the scrum runs smoothly and the issues can be clearly assessed as ready or not ready. Also, new issues can be easily assigned to individuals.

- **Objective**: See background.

- **Acceptance Criteria**: Ensuring smooth and clear scrums. It should also provide clarity on which task is intended for whom.

- **Steps to Reproduce**: Change code in standerd templates.

- **Screenshots/Logs**: -

- **Dependencies**: -

- **Notes**: -

#### Moet dit gedeelte in de issue template? of is dit vanuit chat gpt een suggestie om labels te maken?

- **Use Story Points**: Assign points based on complexity, effort, and uncertainty. A common scale is Fibonacci-like sequence (1, 2, 3, 5, 8, 13, etc.).
   - 3?

- **T-Shirt Sizes**: Assign sizes (XS, S, M, L, XL) if numerical points feel too granular.
   - M?

- **Time Estimates**: Allocate hours or days if the team prefers time-based estimates.
   - 2 hours?

#### Moet dit gedeelte in de issue template? of is dit vanuit chat gpt een suggestie om labels te maken?

- **Type**: feature

- **Status**: in progress

- **Priority**: e.g., low, medium, high, urgent.

- **Sprint**: Label with sprint number/name for easy filtering, like sprint-1, sprint-2.

**Comment by rubenvanpeursem** [comment]
Ziet er goed uit, voor de estimating effort stel ik voor om een schaal van 1-10 te gebruiken voor hoe moeilijk we denken dat het gaat zijn

**Comment by FabianDumitrascu** [comment]
Ja eens @rubenvanpeursem
