### ISSUE TITLE
4. Enroll group in the Egineer in Society project & find out what to do when

### ISSUE THREAD

**Issue by ThijmenStaatsen** [FabianDumitrascu/Cooperative-Drone-Delivery-Cables#23]
### 1. Title:
Enroll group in the Egineer in Society project & find out what to do when

### 2. Description:

- **Objective**: Enroll group in the Egineer in Society project

- **Acceptance Criteria**: Enrolled in a group

**Comment by Bobmarinus** [comment]
Op dit moment van schrijven, 22 april 2024, staat er een deadline voor het vak op **3 mei 2024 18:00**. Echter staat er op brightspace nog niks over wat er precies voor deze deadline moet gebeuren. 

Komende woensdag, 24 april 2024, is het eerste college. Ik wacht deze af en hoop dat we dan meer informatie krijgen over wat deze deadline inhoud. Dan zal ik een update geven.
